### ISSUE TITLE
[Request]: Update the API documentation

### ISSUE THREAD

**Issue by SyedAanif** [SolaceProducts/pubsubplus-go-client#21]
### Feature Description

Thanks for building this API, but as a request can you please update the docs with examples specifically catering to the mTLS needs.

### Use Case

This request is required to have a clear understanding of the certificate based broker connection. Few pointers:
- What should be the format of the certificate file/Keys etc?
- If we are creating certs and keys, what's the need of `key-store-password`?
- Should we just create a `./trust_store` folder with `.pem` files inside and not mention any file name in `trust-path`?
- What's the format of trust_store files?
- Should we create a certificate chain or keep all the certificates as individuals?

**Comment by mvsolace** [comment]
Hi @SyedAanif , can you please raise this request with our support team by contacting support@solace.com? They will be able to help answer your request or guide you to someone that can.

Thank you,
MV

**Comment by solace-brendabutler** [comment]
Two-way TLS authentication (or "client-certificate authentication") is documented here:

https://docs.solace.com/API/API-Developer-Guide-Go/Go-API-Messaging-Service.htm#Client

There are examples of it in this codebase in the test code.  Please see pubsubplus-go-client/test/messaging_service_test.go, and search for either
"connect to the broker using client certificate authentication via authentication strategies"
or
"connect to the broker configured via properties".

**Comment by solace-brendabutler** [comment]
I have submitted a request for the documentation to be augmented with extra info about cert/key file format, and what to do in case the key is in the same file as the certificate, and what to do if there is no password for the private key.

I have also raised Issue https://github.com/SolaceSamples/solace-samples-go/issues/14

**Comment by RagnarPaulson** [comment]
The request for samples is being handled in the SolaceSamples repository.

**Comment by SyedAanif** [comment]
Thanks for the reply, but we chose to use traditional JMS to connect to
Solace broker, because none of the pub-sub clients(in any languages) was
working inside AWS Lambda.

**Comment by Chaymee** [comment]
Added in the samples https://github.com/SolaceSamples/solace-samples-go/issues/14
