### ISSUE TITLE
Fine tune log levels for connection and reconnection events

### ISSUE THREAD

**Issue by tarjanik** [SolaceProducts/pubsubplus-go-client#3]
Hello,

I started using the Go Solace client and I noticed some tweakings that could be done to improve the logging.
When a PubSub+ server connection is broken, I'd always like to see the logs of:
- the connection has just broken
- there is a reconnection attempt going on
- an attempt failed
- an attempt succeeded

First I tried `AddServiceInterruptionListener` `AddReconnectionListener` and `AddReconnectionAttemptListener` with limited success (e.g. not every attempt is triggering the listener)

Then I switched the log level to `logging.SetLogLevel(logging.LogLevelInfo)`. This will print the required information (and more).
What I was suprised about, is that `logging.SetLogLevel(logging.LogLevelWarning)` does not contain the connection errors/retries.

I think it would make sense to increase the log level of such actions, so they can be filtered better with the warning level.

**Comment by mvsolace** [comment]
Hello,

Unfortunately we do not have any plans on changing the log levels and they are working as designed.  For more information on the different log levels and what they represent please see the following docs page [here](https://docs.solace.com/API/API-Developer-Guide/Configuring-Logging.htm?#C-and-Net-api)
