### ISSUE TITLE
ReconnectionAttemptListener is only invoked once, when disconnected

### ISSUE THREAD

**Issue by tarjanik** [SolaceProducts/pubsubplus-go-client#4]
Hi,

The reconnection attempt listener is only called once, when the Solace broker is disconnedted, then it is not actually invoked on reconnection attempts (as repoted in the logs from C code).

`AddReconnectionAttemptListener(listener ReconnectionAttemptListener) uint64`

Steps to reproduce:
- Create a messaging service
- Add a recommection attempt listener
- Disconnect the Solace broker (e.g. stop the docker container)

`ReconnectionAttemptListener` will be called once

- Wait for further attempts (reported by the logs)

`ReconnectionAttemptListener` will not be called for any of the retries

- Connect the Solace broker once again

`ReconnectionListener` will be called.

**Comment by mvsolace** [comment]
Hello,

The single reconnecting/reconnected event is by design and working as intended. As such, there are no current plans to change this in the near future.
