### ISSUE TITLE
Setting ApplicationMessageID Overwrites ApplicationMessageType

### ISSUE THREAD

**Issue by kenanelgaouny** [SolaceProducts/pubsubplus-go-client#5]
Hello 👋 

it looks like the following methods are not behaving as expected:
https://github.com/SolaceProducts/pubsubplus-go-client/blob/acba067eefbadce3c4896baa879d0acde8d47590/internal/ccsmp/ccsmp_message.go#L245-L261

The ApplicationMessageType is being set/retrieved instead of the applicationMessageID

i.e. 
`solClient_msg_setApplicationMsgType` and `solClient_msg_getApplicationMsgType`

instead of:
`solClient_msg_setApplicationMessageId` and `solClient_msg_getApplicationMessageId`

**Comment by mvsolace** [comment]
Hi Kenan,

Thank you for the raising this issue. We will be addressing it with the next release of the API!

**Comment by Mrc0113** [comment]
Thanks for opening this issue @kenanelgaouny. We appreciate you helping us improve the Go client! I just wanted to let you know that we have a developer community forum over at https://solace.community if you have any questions or even want to share what you create. Basically any sort of conversation you wouldn't usually have via a github issue ;) 

Thanks again
