### ISSUE TITLE
Build Issue on Apple silicon(M1)

### ISSUE THREAD

**Issue by vishaljangid1729** [SolaceProducts/pubsubplus-go-client#7]
Hi Team

I am using go1.19.1 on Mac(M1) and am unable to build due to dependencies issues. 

```
$ go version
$ go version go1.19.1 darwin/arm64
```

`go build` output:
```
# solace
/opt/homebrew/Cellar/go/1.19.1/libexec/pkg/tool/darwin_arm64/link: running clang failed: exit status 1
ld: warning: directory not found for option '-L/usr/local/opt/openssl@1.1/lib'
ld: library not found for -lssl
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Thanks
Vishal

**Comment by vishaljangid1729** [comment]
`go env` output: 

```
GO111MODULE="on"
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/b0224754/Library/Caches/go-build"
GOENV="/Users/b0224754/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/b0224754/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/b0224754/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/opt/homebrew/Cellar/go/1.19.1/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/opt/homebrew/Cellar/go/1.19.1/libexec/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.19.1"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/6c/0ptyz43n0q17frnrc345886h0000gn/T/go-build2251362809=/tmp/go-build -gno-record-gcc-switches -fno-common"

```

**Comment by mcardy** [comment]
Hi @vishaljangid1729, thanks for opening the issue! Unfortunately we do not yet support Apple Silicon (M1) in the Go API, so you will see issues/errors right now. It is a feature on our roadmap though so stay tuned! 

The error you are seeing is not caused by lack of M1 support though. OpenSSL is required to build and run apps using the API on Macs. You can install it with homebrew `brew install openssl@1.1`.

**Comment by SyedAanif** [comment]
@mcardy Can you please check [this issue](https://solace.community/discussion/1690/facing-issue-in-building-solacepubsub-in-go-project-in-different-environment), specifically [this comment](https://solace.community/discussion/comment/7159#Comment_7159) on the issue. We are not able to build executable on our laptops. This is impacting our project deliverables.

Prompt response will be highly appreciated.
